### PR TITLE
Qemu 2.10 requires `-U` flag to read volume metadata

### PR DESCRIPTION
**Pull request by GutoVeronezi**
### Description
`Qemu 2.10 added the requirement of a --force-share flag to 'qemu-img info' command when reading information about a disk that is in use by a guest`. After this Qemu release, to obtain the attached disk metadata, we need to use a flag to force information reading.   

This PR intends to add the required flag to the `qemu-img info` command if the qemu version is 2.10+. We can get the Qemu version in the LibvirtConnection.

Fixes: #4024

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

### How Has This Been Tested?
It has been tested locally.

### CODE REVIEW

**Comment by rhtyd** [comment]
@GutoVeronezi what error/issue do you see and on which KVM distro?

**Comment by rafaelweingartner** [comment]
@rhtyd I checked this one with him. The problem happens on Qemu 2.10+. The release notes from Qemu have the following message.
```
Qemu 2.10 added the requirement of a --force-share flag to qemu-img
info when reading information about a disk that is in use by a
guest. We do this a lot in Nova for operations like gathering
information before live migration.

```

The problem is happening when ACS tries to get some info from a volume using qemu-img. Then, one would get the following error.
```
qemu-img: Could not open '/mnt/.../../volumeID': Failed to get shared "write" lock
Is another process using the image?

```

**Comment by rhtyd** [comment]
Okay but which KVM/Linux distro is it reproducible on?

**Comment by GutoVeronezi** [comment]
It has been tested over Ubuntu 18.04 with KVM 2.11.1

**Review by weizhouapache — COMMENTED** [review]
code lgtm
@DaanHoogland @rhtyd we need this in 4.15.0.0 as well.

**Comment by rhtyd** [comment]
Looks like RC4 has been cut, given Ubuntu 18.04 has been around for quite some time should this be considered a blocker?

**Comment by rhtyd** [comment]
@GutoVeronezi @weizhouapache probably too late now - RC4 is cut; in order to get the PR into 4.15, the base branch needs to be changed

**Comment by GutoVeronezi** [comment]
Thanks for the review guys. To us, it is fine if it only goes to master.

**Comment by weizhouapache** [comment]
> Thanks for the review guys. To us, it is fine if it only goes to master.

ok, let's merge this after 4.15.0.0 release

**Review by RodrigoDLopez — APPROVED** [review]
Code LGTM...
I think we need Unit tests to cover these changes... But to do this you'll need to do some changes in many methods. 
Maybe you can do this in another PR?

Another point ... maybe you can better explain how this branch can be tested. 
> It has been tested locally.

Your explanation does not tell us anything related to the tests.

**Comment by GutoVeronezi** [comment]
@RodrigoDLopez to test this enhancement I had used the `create snapshot` API.
With my test instance running, I tried to take a snapshot from the volume. Whitout the `-u` flag I was getting `qemu-img: Could not open '/mnt/...': Failed to get shared "write" lockIs another process using the image?` error.

**Review by GabrielBrascher — APPROVED** [review]
Code LGTM.

However, considering that this impacts versions that have at least ubuntu 18.04 (if I am not mistaken Ubuntu 18.04 gets by default qemu-kvm 2.11). It would be nice to have this on prior LTSs.

Any comment on what branches/releases should we target this one? @rhtyd @weizhouapache @rafaelweingartner and others

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

File: plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/qemu/QemuImg.java [hunk 1]
```diff
@@ -234,14 +235,19 @@ public void create(final QemuImgFile file, final Map<String, String> options) th
...
+                        final Map<String, String> options, final String snapshotName) throws QemuImgException, LibvirtException {
         Script script = new Script(_qemuImgPath, timeout);
         if (StringUtils.isNotBlank(snapshotName)) {
             String qemuPath = Script.runSimpleBashScript(getQemuImgPathScript);
             script = new Script(qemuPath, timeout);
         }
 
         script.add("convert");
+        Long version  = LibvirtConnection.getConnection().getVersion();
+        if (version > 2009000) {
```
Comment (weizhouapache) [inline plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/qemu/QemuImg.java:247]: @GutoVeronezi 
I checked qemu codebase, this is introduced in 2.10.0

so I suggest to use 
```
if (version >= 2010000) {
```

qemu 2.9.1 does not support it.

File: plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/qemu/QemuImg.java [hunk 2]
```diff
@@ -343,10 +349,15 @@ public void commit(final QemuImgFile file) throws QemuImgException {
      *            A QemuImgFile object containing the file to get the information from
      * @return A HashMap with String key-value information as returned by 'qemu-img info'
      */
-    public Map<String, String> info(final QemuImgFile file) throws QemuImgException {
+    public Map<String, String> info(final QemuImgFile file) throws QemuImgException, LibvirtException {
         final Script s = new Script(_qemuImgPath);
         s.add("info");
+        Long version  = LibvirtConnection.getConnection().getVersion();
+        if (version > 2009000) {
```
Comment (weizhouapache) [inline plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/qemu/QemuImg.java:356]: @GutoVeronezi same here.

**Comment by weizhouapache** [comment]
It seem this does not impact NFS-based environments, as they use script files in scripts/storage/qcow2/ to manage volumes/template/snapshots.

I do not know if there are critical issues with RBD-based environments. maybe @wido @GabrielBrascher know.

**Comment by wido** [comment]
> It seem this does not impact NFS-based environments, as they use script files in scripts/storage/qcow2/ to manage volumes/template/snapshots.
> 
> I do not know if there are critical issues with RBD-based environments. maybe @wido @GabrielBrascher know.

NFS is also impacted if you have enabled file locking (which most NFS envs have enabled).

RBD isn't impacted in any case as it doesn't use QCOW2.

**Comment by DaanHoogland** [comment]
> Trillian test result (tid-3448)
> Environment: kvm-centos7 (x2), Advanced Networking with Mgmt server 7
> Total time taken: 42227 seconds
> Marvin logs: [blueorangutan/acs-prs@`trillian` pr4567-t3448-kvm-centos7.zip (download)](https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4567-t3448-kvm-centos7.zip)
> Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
> Intermittent failure detected: /marvin/tests/smoke/test_privategw_acl.py
> Smoke tests completed. 84 look OK, 2 have error(s)
> Only failed tests results shown below:
> Test 	Result 	Time (s) 	Test File
> test_01_deploy_kubernetes_cluster 	`Failure` 	3624.07 	test_kubernetes_clusters.py
> test_04_deploy_and_scale_kubernetes_cluster 	`Failure` 	22.51 	test_kubernetes_clusters.py
> test_07_deploy_kubernetes_ha_cluster 	`Failure` 	26.61 	test_kubernetes_clusters.py
> test_08_deploy_and_upgrade_kubernetes_ha_cluster 	`Failure` 	0.04 	test_kubernetes_clusters.py
> test_09_delete_kubernetes_ha_cluster 	`Failure` 	0.04 	test_kubernetes_clusters.py
> ContextSuite context=TestKubernetesCluster>:teardown 	`Error` 	78.68 	test_kubernetes_clusters.py
> test_04_rvpc_privategw_static_routes 	`Failure` 	868.50 	test_privategw_acl.py

@GutoVeronezi , can you check the private gateway error (you can ignore the kubernetes ones)?

**Comment by weizhouapache** [comment]
> > It seem this does not impact NFS-based environments, as they use script files in scripts/storage/qcow2/ to manage volumes/template/snapshots.
> > I do not know if there are critical issues with RBD-based environments. maybe @wido @GabrielBrascher know.
> 
> NFS is also impacted if you have enabled file locking (which most NFS envs have enabled).
> 
 yes, the scripts in scripts/storage/qcow2/ has been changed to support -U in #4068
I have tested some actions on vms/volumes/templates on ubuntu 20.04, look ok without this pr.

> RBD isn't impacted in any case as it doesn't use QCOW2.
@wido as far as I know, this impacts RAW format as well.
`qemu.convert` is used for RBD in plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
`q.convert` in plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java

maybe there is no issue as in most cases vm is stopped.

**Comment by weizhouapache** [comment]
> > Trillian test result (tid-3448)
> > Environment: kvm-centos7 (x2), Advanced Networking with Mgmt server 7
> > Total time taken: 42227 seconds
> > Marvin logs: [blueorangutan/acs-prs@`trillian` pr4567-t3448-kvm-centos7.zip (download)](https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4567-t3448-kvm-centos7.zip)
> > Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
> > Intermittent failure detected: /marvin/tests/smoke/test_privategw_acl.py
> > Smoke tests completed. 84 look OK, 2 have error(s)
> > Only failed tests results shown below:
> > Test 	Result 	Time (s) 	Test File
> > test_01_deploy_kubernetes_cluster 	`Failure` 	3624.07 	test_kubernetes_clusters.py
> > test_04_deploy_and_scale_kubernetes_cluster 	`Failure` 	22.51 	test_kubernetes_clusters.py
> > test_07_deploy_kubernetes_ha_cluster 	`Failure` 	26.61 	test_kubernetes_clusters.py
> > test_08_deploy_and_upgrade_kubernetes_ha_cluster 	`Failure` 	0.04 	test_kubernetes_clusters.py
> > test_09_delete_kubernetes_ha_cluster 	`Failure` 	0.04 	test_kubernetes_clusters.py
> > ContextSuite context=TestKubernetesCluster>:teardown 	`Error` 	78.68 	test_kubernetes_clusters.py
> > test_04_rvpc_privategw_static_routes 	`Failure` 	868.50 	test_privategw_acl.py
> 
> @GutoVeronezi , can you check the private gateway error (you can ignore the kubernetes ones)?

@DaanHoogland it should have been fixed.

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by wido** [comment]
Can you also fix this in *resizevolume.sh* ?

https://github.com/apache/cloudstack/blob/master/scripts/storage/qcow2/resizevolume.sh#L181

**Comment by GutoVeronezi** [comment]
> Can you also fix this in _resizevolume.sh_ ?
> 
> https://github.com/apache/cloudstack/blob/master/scripts/storage/qcow2/resizevolume.sh#L181

@wido done.

**Review by GabrielBrascher — APPROVED** [review]
Code LGTM.

Manually tested the update on `resizevolume.sh`; it retrieves the correct qemu version and executes `qemu-img` command appending `-U` as expected.

**Comment by GabrielBrascher** [comment]
@blueorangutan package

**Review by GabrielBrascher — COMMENTED** [review]
All tests are failing due to:

```
[ERROR] /home/travis/build/apache/cloudstack/plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java:[4304,48] error: unreported exception LibvirtException; must be caught or declared to be thrown

[ERROR] /home/travis/build/apache/cloudstack/plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java:[4310,63] error: unreported exception LibvirtException; must be caught or declared to be thrown
```

It is necessary to handle LibvirtException at `LibvirtComputingResource.java:4310`

**Comment by GutoVeronezi** [comment]
@GabrielBrascher I rebased the PR and fixed it.

I will ask you to take a look at the commit db1e0f49dc06d16218ce61d9ef6a025075710d8e, which introduced the error you reported. I am wondering, how this commit was merged if Travis explicitly says that `The build canceled. This is a change from the previous build, which errored.`?

**Comment by weizhouapache** [comment]
> @GabrielBrascher I rebased the PR and fixed it.
> 
> I will ask you to take a look at the commit [db1e0f4](https://github.com/apache/cloudstack/commit/db1e0f49dc06d16218ce61d9ef6a025075710d8e), which introduced the error you reported. I am wondering, how this commit was merged if Travis explicitly says that `The build canceled. This is a change from the previous build, which errored.`?

@GutoVeronezi the issue is caused by https://github.com/apache/cloudstack/pull/4567/files#diff-8c9bad5e83a17ce03945d04eea177a39d57f52b92c32cdc86888cedbc49d9a84R355
```
        Long version  = LibvirtConnection.getConnection().getVersion();
```
good you have fixed it.

**Comment by GabrielBrascher** [comment]
@GutoVeronezi thanks for rebasing and fixing the compilation issue.

Answering your question:

You had correctly addressed most of the callers by adding `LibvirtException e` at their respective `catch` blocks. However, it was missing LibvirtException at the cath block in `LibvirtComputingResource.java`. Therefore, the error that I reported was a compilation error caused due to the addition of `LibvirtException` at the method's _throws_ that was not handled at LibvirtComputingResource.java (lines 4304 and 4310).

Commit that added the mentioned `LibvirtExeption`:
https://github.com/apache/cloudstack/blob/1c1d3566827ba75e5cf17a1c6fe0789a959a501d/plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/qemu/QemuImg.java#L352

I don't understand how commit https://github.com/apache/cloudstack/commit/db1e0f49dc06d16218ce61d9ef6a025075710d8e would introduce that error. At that time method `QemuImg.info` was not throwing `LibvirtException`.

Additionally, checking at PR #4656 all looks good: Jenkins, Travis, and Trilian tests passed (https://github.com/apache/cloudstack/pull/4656/commits).

image

**Comment by GabrielBrascher** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@GutoVeronezi  tested ok.
There are ignored NPE when migrate vm with datadisk. It is caused by commit db1e0f4 
Fixed by #4800

**Comment by GabrielBrascher** [comment]
@GutoVeronezi Travis now points to `ScaleIOStorageAdaptor.java` (lines 271 & 365). Can you please re-check it?

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:17 min (Wall Clock)
[INFO] Finished at: 2021-03-11T15:59:17Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project cloud-plugin-hypervisor-kvm: Compilation failure: Compilation failure: 
[ERROR] /home/travis/build/apache/cloudstack/plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptor.java:[271,24] error: unreported exception LibvirtException; must be caught or declared to be thrown
[ERROR] /home/travis/build/apache/cloudstack/plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptor.java:[365,24] error: unreported exception LibvirtException; must be caught or declared to be thrown
```

**Comment by GutoVeronezi** [comment]
@GabrielBrascher done.

I looked for more places that needed to handle it, but found none.

**Comment by GabrielBrascher** [comment]
Thanks, @GutoVeronezi!

**Review by GabrielBrascher — APPROVED** [review]
Tests indicate that all `LibvirtException` have been handled. LGTM.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
> Tests indicate that all `LibvirtException` have been handled. LGTM.

@GabrielBrascher I merged based on this comment of yours, but then we had some internal discussion on whether it was tested enough. I don't think any of the failures above are due to this change, but still, can you comment a bit more on testing please? cc @GutoVeronezi
