### ISSUE TITLE
UI: Search input field does not work after updating to 4.22

### ISSUE THREAD

**Issue by phsm** [apache/cloudstack#12729]
### problem

The search functionality in the UI has stopped working after updating to Cloudstack 4.22.

The search functionality does not work on these pages:
- Accounts
- Templates
- ISOs
- Volumes
- Volume snapshots
- Snapshot policies
- Shared filesystems

The search functionality works on every other page that has search field.

When attempting searching on the affected pages, the following exception appears in the browser console:
```
SearchView.vue:1596 TypeError: o.forEach is not a function
    at Proxy.onSearch (AutogenView.vue:2001:21)
    at v (runtime-core.esm-bundler.js:155:22)
    at w (runtime-core.esm-bundler.js:164:21)
    at le (runtime-core.esm-bundler.js:721:9)
    at Proxy.onSearch (SearchView.vue:1596:12)
    at v (runtime-core.esm-bundler.js:155:22)
    at w (runtime-core.esm-bundler.js:164:21)
    at le (runtime-core.esm-bundler.js:721:9)
    at W (Search.js:71:7)
    at v (runtime-core.esm-bundler.js:155:22)
P0 @ runtime-core.esm-bundler.js:226
T0 @ runtime-core.esm-bundler.js:204
v @ runtime-core.esm-bundler.js:158
w @ runtime-core.esm-bundler.js:164
le @ runtime-core.esm-bundler.js:721
onSearch @ SearchView.vue:1596
v @ runtime-core.esm-bundler.js:155
w @ runtime-core.esm-bundler.js:164
le @ runtime-core.esm-bundler.js:721
W @ Search.js:71
v @ runtime-core.esm-bundler.js:155
w @ runtime-core.esm-bundler.js:164
le @ runtime-core.esm-bundler.js:721
N @ Input.js:219
v @ runtime-core.esm-bundler.js:155
w @ runtime-core.esm-bundler.js:164
r @ runtime-dom.esm-bundler.js:369
```

### versions

Cloudstack version 4.22.1
Browsers: Chrome, Firefox

### The steps to reproduce the bug

1. Open any of the pages, for example Accounts.
2. Type something into the search bar.
3. Nothing happens visually. At the same time, an error is emitted into the browser console.
...

**Comment by shwstppr** [comment]
@phsm This should be fixed by https://github.com/apache/cloudstack/pull/12146

And before people may start pointing out, this was caused due to a change I made in 4.20.2 and later, https://github.com/apache/cloudstack/pull/11576

You may test one of the nightly builds here to verify the fix, https://download.cloudstack.org/testing/nightly/

**Comment by phsm** [comment]
Thank you.

Indeed, this patch seem to have fixed it.
