### PR TITLE
NSX: add native route-based Site-to-Site VPN support

### PR DESCRIPTION
**Pull request by Dogface2k**
This PR implements native, route-based Site-to-Site VPN for NSX NAT-mode VPCs. The VPN terminates on the VPC's NSX Tier-1 gateway; the CloudStack virtual router remains outside the IPsec data path.

The implementation makes the existing built-in `Vpn/Nsx` service mapping functional and supersedes the capability-removal approach in the closed #13765. It does not change seeded offerings or the database schema.

The main lifecycle is provider-dispatched through `Site2SiteVpnServiceProvider` instead of adding another provider-specific branch to `Site2SiteVpnManagerImpl`:

- gateway creation validates or acquires a dedicated public IP, records whether NSX owns that allocation, and creates a deterministic Tier-1 `IPSecVpnService` and local endpoint;
- connection start validates CloudStack crypto policy, creates NSX IKE/tunnel/DPD profiles, a `RouteBasedIPSecVpnSession`, and a VTI named `default-tunnel-interface`;
- each remote CIDR receives a Tier-1 static route and a `NO_SNAT` rule so traffic is not rewritten by the VPC's catch-all source NAT before entering the tunnel;
- stop disables the session and removes connection routes/NAT exemptions; restart recreates them; permanent deletion also removes the session and profiles;
- gateway and VPC teardown remove VPN objects before the Tier-1 gateway is deleted;
- a scheduled status poll maps NSX detailed session status back to CloudStack connection state without allowing a transient query failure to corrupt the last known state.

The public endpoint is intentionally separate from the VPC source-NAT address. NSX requires the IPsec local endpoint to differ from the Tier-1 uplink address. Auto-acquired endpoint addresses are released on gateway deletion; operator-supplied addresses are detached but not released.

Compatibility and failure handling are explicit:

- the new provider SPI methods have defaults, preserving source compatibility for the existing virtual-router implementation and test/extension implementors; NSX opts in explicitly;
- legacy gateway rows without an ownership marker retain the historical virtual-router fallback;
- persisted provider ownership prevents an offering change from redirecting an existing gateway to a different implementation;
- gateway creation refuses to adopt a pre-existing deterministic NSX service and reports ambiguous rollback state instead of silently releasing an address that may already be active;
- Tier-1 VPN mutations share a per-gateway lock with Tier-1 teardown;
- PSKs are excluded from CloudStack command logging while remaining present on the agent wire payload;
- unsupported algorithms, invalid lifetimes, oversized PSKs, missing VPC/gateway rows, and deterministic VTI collisions fail with specific errors.

The Tier-0 must redistribute `TIER1_IPSEC_LOCAL_ENDPOINT` routes for the dedicated gateway address to be externally reachable.

Related context: #13764 and the superseded closed PR #13765.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):

Not applicable: the UI change adds three optional provider fields to the existing canonical VPN-connection details renderer and localization path; it adds no component, style, layout, control, action, or client-side behavior.

### How Has This Been Tested?

All current local validation is bound to exact PR head `a70061fef3dc040b31e72cdbf23b22c44f994a16`, targeting `main`, with OpenJDK 17.0.19 and Maven 3.9.12. The local branch, fork branch, and GitHub PR head are identical and the worktree/index are clean.

The PR merge base is `4f117071c9397b1e4714c8fb61c384883c872842`. The refreshed target used for the final conflict audit is `dd3427d91401f820ba5746403696a6146ab42328`; its three changed paths do not overlap any of this PR's 43 paths, and `git merge-tree --write-tree HEAD origin/main` completes without conflict.

Local results on the exact head:

```text
Focused VPN/NSX tests:
Site2SiteVpnManagerImplTest  65 passed
NsxElementTest               56 passed
NsxApiClientTest             39 passed

Affected 34-module clean reactor:
8,486 tests; 0 failures; 0 errors; 11 skipped
NSX plugin: 215 tests; 0 failures; 0 errors; 0 skipped
Server: 3,643 tests; 0 failures; 0 errors; 5 skipped

Full developer/systemvm/simulator/noredist reactor:
165 modules: BUILD SUCCESS
13,909 tests; 0 failures; 0 errors; 13 skipped

Full quality/JaCoCo reactor:
165 modules: BUILD SUCCESS
Normal reports: 13,909 tests; 0 failures; 0 errors; 13 skipped
Instrumented reports: 13,909 tests; 0 failures; 0 errors; 13 skipped
Aggregate line coverage: 24.73% (repository grade D)

UI (Node 16.20.2 / npm 8.19.4):
production build passed
lint passed with zero errors
4 suites / 175 unit tests passed

Apache RAT:
11,111 resources; 0 unapproved/unknown licenses

Pre-commit:
standard all-files hooks passed
manual-stage hooks passed

Packaging:
el8, el9, el10, Debian and SUSE 15 passed (Blue Orangutan SL-JID 18806)
```

The full Maven build used the repository's `developer,systemvm` profile with `-Dsimulator -Dnoredist`; the quality run added the repository's `quality` profile and was followed by `scripts/coverage-grade.sh` against the generated aggregate XML. The UI install's mechanical lockfile-format rewrite was discarded after verification; no generated or dependency artifact is part of the PR.

Test sensitivity was checked rather than inferred:

- temporarily restoring the unsafe broad Tier-1 exception-to-null behavior made `NsxApiClientTest.testDeleteVpnServicePropagatesTier1TransportFailureBeforeCleanup` fail for the intended missing exception; restoring the fix made it pass;
- temporarily removing the Remote Access VPN provider guard made `RemoteAccessVpnManagerImplTest.createRemoteAccessVpnRejectsVpcWithoutMappedProviderBeforePersistence` fail before persistence; restoring the guard made it pass;
- end-to-end failure tests verify that a non-`NotFound` Tier-1 transport failure propagates through the NSX client/element/manager path and preserves the ownership marker, public IP, and gateway row.

Two low-value tests were removed: one asserted mocked DAO self-interactions without executing its SQL/result contract, and one duplicated stronger NSX ownership cases already exercised through `NsxElementTest`.

The NSX suite covers the management-server/agent command paths, including normal and logger Gson serialization plus deserialization of the real `Command[]` payload, proving that the PSK remains in the command wire JSON while `@LogLevel(Off)` excludes it from logger serialization.

Live validation already recorded on this PR remains applicable to this implementation:

- on 4.23.0.0-SNAPSHOT with NSX 4.2.4, disposable NAT-mode VPC resources exercised gateway/connection creation, two immediate resets, ordered connection/customer-gateway/VPN-gateway cleanup, endpoint release, active-connection VPC teardown, and the unsupported Remote Access VPN guard;
- separate end-to-end traffic validation between `192.168.46.5` and `10.35.0.1` succeeded in both directions over the FortiGate/NSX route, with the CloudStack connection remaining `Connected`;
- no production VPN connection was modified during the disposable lifecycle run.

#### How did you try to break this feature and the system with this change?

The negative and compatibility coverage exercises the failure boundaries rather than only the happy path:

- focused endpoint-conflict tests prove rejection of inactive, source-NAT, and port-forwarding addresses before NSX mutation;
- auto-acquired and operator-supplied endpoint addresses have different, verified release behavior;
- partial and ambiguous gateway creation failures preserve enough ownership state for safe operator recovery and never adopt an unrelated deterministic NSX service;
- connection creation rolls back partial sessions, routes, and NAT exemptions;
- changed peer CIDR lists do not strand old routes or `NO_SNAT` rules during deletion;
- deterministic VTI address collisions are detected against live Tier-1 sessions and fail closed;
- invalid/unsupported cipher, hash, DH group, IKE version, lifetime, and PSK values are rejected before an NSX mutation;
- stop, restart, reset, permanent connection deletion, gateway deletion, missing-row cleanup, and full VPC teardown are separately covered;
- source-NAT rule demotion preserves the complete original rule and sequence, and the exact sequence is restored when the final VPN exemption is removed;
- operator-created VPN services on the Tier-1 are not swept during CloudStack teardown;
- provider ownership remains stable if an offering mapping changes after gateway creation;
- legacy virtual-router VPN selection and command generation remain covered, while NSX-owned connections are excluded from virtual-router commands and monitoring;
- repeated status-query failures alert without forcing a false state transition, and successful `UP`, `DOWN`, degraded, and not-found results map to the intended CloudStack states;
- missing VPC or gateway state fails start/stop explicitly instead of reporting a false success, while permanent deletion remains idempotent for cleanup.

No generic CloudStack command proxy, broad exception suppression, schema migration, retry of an ambiguous CloudStack mutation, or unrelated UI/CKS/network-offering change is included.

The focused manager tests cover the established single-source-NAT virtual-router fallback and the NSX provider-owned endpoint path through `testCreateVpnGatewayAcceptsValidProviderOwnedIp`. The focused ownership tests do not separately assert system-address, static-NAT, firewall, load-balancer, legacy system-VM source-NAT filtering, or multiple-candidate selection branches; those are not claimed as focused regression proof.

### CODE REVIEW

**Comment by Dogface2k** [comment]
### Follow-up validation and lifecycle hardening

Commit `98cd4ed6f4` adds the lifecycle hardening identified by live NSX validation.

- The existing marked-for-deletion retry is now shared by route-based session creation and the complete static-route/NO_SNAT programming operation. It remains bounded at 24 attempts with a 15-second interval.
- `NsxApiClientTest.testAddVpnConnectionRoutesRetriesMarkedForDeletion` forces the NSX marked-for-deletion response during route creation and verifies the deterministic route is retried before NO_SNAT programming continues.
- State changes use a read-modify-write of the existing route-based session, preserving the mandatory `tunnel_interfaces` field implicated by the pre-deploy failure.
- VPN connection, gateway, customer-gateway, and VPC lifecycle operations use VPC-scoped synchronization and deterministic cleanup.

Live validation on 4.22.1.0 with NSX 4.2.4 used an intentionally unreachable RFC 5737 test peer. The connection reached `Disconnected`; the first reset reproduced the marked-for-deletion 431, the same reset succeeded after the purge window, and connection/customer-gateway/VPN-gateway/VPC deletion completed with the dedicated test IP released. No production connection was modified, and no tunnel-traffic success is claimed from this test peer.

The supplied pre-deploy `tunnel_interfaces` error is a distinct historical failure; the current read-modify-write path passed the stop half of the live reset test. The local checkout has no JDK/Maven executable, so the new focused test must be run by repository CI; `git diff --check` is clean.

**Comment by Dogface2k** [comment]
### Additional live data-plane evidence

Operator-side testing between `192.168.46.5` and `10.35.0.1` succeeded in both directions over the documented FortiGate/NSX path. The original direction returned 2/2 ICMP replies with 0% loss and 17.45 ms average latency; traceroute showed `6x.xxx.xxx.xxx` (FortiGate) followed by `10.35.0.1`.

CloudStack connection 8 remained `Connected` before and after. This is positive bidirectional endpoint-reachability evidence through the VPN path.

**Comment by DaanHoogland** [comment]
@Dogface2k , want to address the co-pilot comments ?

File: plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxServiceImpl.java [hunk 1]
```diff
@@ -196,6 +282,173 @@ public boolean deleteFirewallRules(Network network, List<NsxNetworkRule> netRule
...
+     * NSX ownership; duplicate polling in a multi-server setup is tolerated, as state transitions
+     * are serialized by the row lock in transitionVpnConnectionState
+     */
+    protected class VpnStatusPollTask extends ManagedContextRunnable {
+        @Override
+        protected void runInContext() {
+            try {
+                Set<Long> polledConnectionIds = new HashSet<>();
+                List<Site2SiteVpnConnectionVO> connections = site2SiteVpnConnectionDao.listAll();
+                for (Site2SiteVpnConnectionVO connection : connections) {
```
[the remark this answers is not in the document]
Comment (Dogface2k) [reply plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxServiceImpl.java]: Addressed in 4cea137c21. The poller now queries Site2SiteVpnConnectionDao.listByStates(Pending, Connecting, Connected, Disconnected), so terminal rows are filtered by SQL instead of loading the complete table. NSX ownership remains checked from the persisted IP detail in NsxServiceImpl; keeping that plugin-specific marker out of the shared engine DAO avoids coupling the schema layer to the NSX plugin. Added DAO criteria coverage and an exact poller-query test. Full affected suites pass: engine/schema 385/385 and NSX plugin 202/202, with checkstyle clean.

File: plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxServiceImpl.java [hunk 2]
```diff
@@ -16,49 +16,135 @@
...
+        return true;
+    }
+
+    @Override
+    public boolean stop() {
+        if (Objects.nonNull(vpnStatusPollExecutor)) {
+            vpnStatusPollExecutor.shutdownNow();
+        }
+        return super.stop();
+    }
```
[the remark this answers is not in the document]
Comment (Dogface2k) [reply plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxServiceImpl.java:162]: Addressed in 4cea137c21. Executor creation now belongs to synchronized start(); stop() atomically clears and shuts down the current executor, and a subsequent same-JVM start creates and schedules a fresh one. A scheduling failure also shuts down the newly created executor before propagating. Added a focused start -> stop -> start test that verifies the first executor is shut down and the replacement is scheduled and later shut down. Full affected suites pass: engine/schema 385/385 and NSX plugin 202/202, with checkstyle clean.

**Comment by Dogface2k** [comment]
@DaanHoogland Addressed both Copilot findings in 4cea137c21: the poller now uses a state-filtered DAO query, and its executor is restart-safe across start/stop/start. Added focused DAO, lifecycle, and status-mapping tests; the complete affected suites pass (engine/schema 385/385 and NSX plugin 202/202), with checkstyle clean. Both review threads are now resolved.

File: plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxElement.java [hunk 3]
```diff
@@ -941,4 +987,283 @@ public List<Class<?>> getCommands() {
...
+    }
+
+    private void releaseAutoAcquiredVpnGatewayIp(IPAddressVO ip) {
+        boolean disassociated = ipAddressManager.disassociatePublicIpAddress(ip, CallContext.current().getCallingUserId(),
+                CallContext.current().getCallingAccount());
+        if (!disassociated) {
+            throw new CloudRuntimeException(String.format("Failed to disassociate auto-acquired VPN gateway IP %s", ip.getAddress()));
+        }
+        userIpAddressDetailsDao.removeDetail(ip.getId(), NSX_VPN_GATEWAY_IP_DETAIL);
+    }
```
[the remark this answers is not in the document]
Comment (Dogface2k) [reply plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxElement.java:1190]: Reviewing

[the remark this answers is not in the document]
Comment (DaanHoogland) [reply plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxElement.java:1190]: @Dogface2k , I’ve seen this feedback from co-pilot before . I don’t have an assessment of its value. But as a generic comment it makes sense. The question you should ask is, “would any reconnect or restart have this call as an asynchronous result. If so, take the comment serious.

[the remark this answers is not in the document]
Comment (Dogface2k) [reply plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxElement.java:1190]: @DaanHoogland Thanks I traced that specific possibility. Reset, reconnect, restart and stop operate only on the VPN connection/session and never call `releaseVpnGatewayIp`. The release path is reached only during gateway-creation rollback, explicit gateway deletion, or VPC teardown. The background VPC teardown runs as a `ManagedContextRunnable` using the system user/account, and `CallContext.current()` already registers a system context when none exists. API-triggered deletion retains its propagated caller context. The ownership marker is also removed only after disassociation succeeds, so a failed release remains recoverable. I therefore don't think an additional fallback or provider-SPI signature change is warranted here. (false positive)

**Comment by Dogface2k** [comment]
Live end-to-end validation completed against the deployed 4.23.0.0-SNAPSHOT build with NSX 4.2.4, using disposable account-scoped resources.\n\n- Created an NSX NAT-mode VPC, tier, dedicated VPN gateway endpoint and route-based connection.\n- Reset the connection immediately after creation twice. Both reset jobs completed successfully in about 16 seconds, directly exercising the marked-for-deletion retry and route-based session update paths.\n- Deleted the connection, customer gateway and VPN gateway; the dedicated endpoint address was released.\n- Repeated teardown with an active VPN connection and deleted the VPC. The Tier-1 VPN service, session, gateway record, connection record and endpoint address were all absent afterward.\n- Confirmed the NSX Remote Access VPN capability guard rejects the unsupported provider before persisting a remote-access VPN record.\n- Existing bidirectional routed-tunnel traffic evidence remains unchanged; no production VPN connection was modified during this disposable lifecycle run.\n\nThis completes the live control-plane lifecycle validation for the scope of this PR. Connection/tunnel already has E2E

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@Dogface2k fyi
```
09:45:43 [INFO] -------------------------------------------------------------
09:45:52 [ERROR] COMPILATION ERROR : 
09:45:52 [INFO] -------------------------------------------------------------
09:45:52 [ERROR] /jenkins/workspace/acs-deb-pkg-builder/server/src/test/java/com/cloud/network/vpn/Site2SiteVpnManagerImplTest.java:[362,8] error: cannot find symbol
09:45:52   symbol:   class ArgumentCaptor
09:45:52   location: class Site2SiteVpnManagerImplTest
09:45:52 [ERROR] /jenkins/workspace/acs-deb-pkg-builder/server/src/test/java/com/cloud/network/vpn/Site2SiteVpnManagerImplTest.java:[362,62] error: cannot find symbol
09:45:52   symbol:   variable ArgumentCaptor
09:45:52   location: class Site2SiteVpnManagerImplTest
09:45:52 [INFO] 2 errors 
```
(the github action output can be inconvenient)

**Comment by Dogface2k** [comment]
Reviewing one final time.

**Comment by Dogface2k** [comment]
@blueorangutan package

File: api/src/main/java/org/apache/cloudstack/api/response/Site2SiteVpnConnectionResponse.java [hunk 4]
```diff
@@ -144,6 +144,18 @@ public class Site2SiteVpnConnectionResponse extends BaseResponse implements Cont
...
+    private String localVtiIp;
+
+    @SerializedName(ApiConstants.PEER_VTI_IP)
+    @Param(description = "The peer-side virtual tunnel interface IP address", since = "4.23.0.0")
+    private String peerVtiIp;
+
+    @SerializedName(ApiConstants.VTI_PREFIX_LENGTH)
+    @Param(description = "The virtual tunnel interface network prefix length", since = "4.23.0.0")
+    private Integer vtiPrefixLength;
+
```
Comment (DaanHoogland) [inline api/src/main/java/org/apache/cloudstack/api/response/Site2SiteVpnConnectionResponse.java:158]: i don’t think this will make the version claimed in the ‘since’ attributes here (i.e. “4.23.0.0”)

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by vishesh92** [comment]
@blueorangutan test
